package utils;

import java.util.ArrayList;
import javax.swing.JFrame;
import mulan.data.MultiLabelInstances;

/**
 * 
 * @author Jose Maria Moyano Murillo
 */
public class EmergentOutput extends javax.swing.JFrame {

    ArrayList<String> metricList, metricList1, metricList2;
    ArrayList<MultiLabelInstances> listDatasets;
    
    MultiLabelInstances dataset, datasetTrain, datasetTest;
    int posx, posy;
    
    String[] info;
    boolean isMeka;
     
   
    // IR per labelset
    public EmergentOutput(MultiLabelInstances dataset, int posx, int posy, 
            String[] args, ArrayList<String> labelNames, 
            ImbalancedFeature[] labelFrequency, boolean isMeka)
    {
        this.dataset = dataset;
        this.posx = posx;
        this.posy = posy;
        this.info = args;        
        this.isMeka = isMeka;
        
        this.setUndecorated(true);
        initComponents();
         
        printInformation(labelNames,labelFrequency);
        
        if(labelNames.size()>10)
        {
            this.setBounds(10, 30, 700, 600);
        }
        else{
            if(posy > 180 && posx<700) {
                this.setBounds(posx, posy-180, 600, 200);
            }
            else if (posy > 180 && posx>700 ) {
                this.setBounds(posx-500, posy, 600, 200);
            }
            else {
                this.setBounds(posx,posy+490,600,200);
            }
        }
    }
    
         
    //IR per labelset
    private void printInformation(ArrayList<String> labelNames, ImbalancedFeature[] imbalancedData)
    {
        String tabs ="\t"+"\t" +"\t";

        int nRepeats = Integer.parseInt(info[1]);
        double value = nRepeats*1.0/dataset.getNumInstances();
        
        jTextArea1.append("Labelset: "+tabs+ info[0]+"\n");
        jTextArea1.append("# Labels: "+tabs+labelNames.size()+"\n");
        
        
        jTextArea1.append("Frequency: "+tabs+ util.Truncate_values_aprox_zero(Double.toString(value), 5)  +"\n");
        jTextArea1.append("# Examples: " +tabs+info[1]+"\n");
        
        ImbalancedFeature current;
        double freq;
        int repeat, id_label=1;
        
        for(int i=0;i<labelNames.size(); i++)
        {
            current = util.Get_label_x_labelname(labelNames.get(i), imbalancedData);
              
            if (current != null)
            {
                repeat = current.getAppearances();
                freq = repeat*1.0/dataset.getNumInstances();
            
                jTextArea1.append("--------------------------------------------------------------------------------------------------------------------------" +"\n");
                jTextArea1.append("Label "+id_label +":  "+tabs+current.getName()+" \n");
                
                jTextArea1.append("Frequency:"+ tabs+ util.Truncate_values_aprox_zero(Double.toString(freq), 5) +"\n");
                  
                jTextArea1.append("# Examples: "+tabs+ repeat +"\n");
                  
                id_label++; 
            }
        } 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Output values"));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextArea1FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextArea1FocusLost
        this.setVisible(false);
    }//GEN-LAST:event_jTextArea1FocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
