/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import org.tc33.jheatchart.HeatChart;

/**
 *
 * @author oscglezm
 */
public class heatmap extends javax.swing.JFrame {

    /**
     * Creates new form heatmap
     */
    public heatmap() {
        
               
        initComponents();
        jchart_image();
        
        
    }

    public void jchart_image()
    {
    // Create some dummy data.
    double[][] data = new double[][]{{0.3,0.2,0.3,0.4,0.5,0.2,1},
                                     {0.2,0.3,0.4,0.5,0.6,0.2,1},
                                     {0.3,0.4,0.5,0.6,1,0.5,1},
                                     {0.3,0.4,0.1,0.6,1,0.5,1},
                                     {0.4,0.5,0.6,0.1,1,1,1}};
    
    // Create our heat chart using our data.
    HeatChart chart = new HeatChart(data);
    
    // Customise the chart.
    chart.setTitle("Esto es una prueba");
    chart.setXAxisLabel("X Axis");
    chart.setYAxisLabel("Y Axis");
    chart.setAxisColour(Color.black);
    chart.setAxisValuesColour(Color.black);
   // chart.setColourScale(2);
   // chart.setShowXAxisValues(false);
    chart.setCellSize(new Dimension(30,30));
    //chart.setBackgroundColour(Color.white);
    
    chart.setHighValueColour(Color.black);
    chart.setLowValueColour(Color.red);
    //chart.setAxisThickness(1);
    
     
    chart.setChartMargin(30);
   
            
    jPanel1.setSize(500,500);
   //jLabel1.setSize(100,100);
    
    
        System.out.println(chart.getCellSize().height + " "+ chart.getCellSize().width);
    
    ImageIcon temp = new ImageIcon(chart.getChartImage());
    jLabel1.setIcon(temp);
    
        System.out.println("ANCHO DE LA IMAGEN "+temp.getIconWidth());
        System.out.println("LARGO DE LA IMAGEN "+temp.getIconHeight());
        
       


    
    
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(heatmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(heatmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(heatmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(heatmap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new heatmap().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
